name: Browser tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * 2'

jobs:
  build:
    name: Integration tests in the browser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: |
          npm install
      - name: Start local server
        run: |
          npm i -g serve
          serve -l 8080 &
      - run: npm run cypress:coverage
      - uses: codecov/codecov-action@v3
